name: "mosaico-testing"
services:
  mosaico-pg-testing:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mosaico
    ports:
      - "6543:5432"
    volumes:
      - mosaico-testing-pg-data:/var/lib/postgresql/data
    networks:
      - mosaico-testing


volumes:
  mosaico-testing-pg-data:

networks:
  mosaico-testing:
    name: mosaico-testing


